### ISSUE TITLE
should use `errors.Cause(err)` instead of `err` to check for retryable error

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach-go#16]
to allow this code to work correctly:

``` go
if err := tx.Exec("...."); err != nil {
    return errors.Wrap(err, "during insert")
}
```

**Comment by andreimatei** [comment]
I sympathize with the desire, but I don't think we should add a dependency on the `pkg/errors` package.
What I'd do is comment on the `ExecuteTx` to tell people that they can't do that. The need for a comment explaining what errors the closure should return has already arisen.
