### ISSUE TITLE
Cannot be used in conjunction with github.com/lib/pq

### ISSUE THREAD

**Issue by ericchiang** [cockroachdb/cockroach-go#17]
Attempting to use this for a project where I'm hoping to also support postgres as well as cockroach db. However, since this package imports "github.com/cockroachdb/pq" it's impossible to also register the "github.com/lib/pq" postgres driver. The registration panics because they both want to be the "postgres" driver.

```
panic: sql: Register called twice for driver postgres

goroutine 1 [running]:
panic(0x714d60, 0xc420010d50)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
database/sql.Register(0x76b2ba, 0x8, 0xabda60, 0xaefe88)
	/usr/local/go/src/database/sql/sql.go:45 +0x1b2
github.com/lib/pq.init.1()
	/home/eric/src/github.com/lib/pq/conn.go:44 +0x5c
github.com/lib/pq.init()
	/home/eric/src/github.com/lib/pq/user_posix.go:25 +0x62f
github.com/coreos/dex/storage/sql.init()
```

What's the reason for using the fork? Is there a plan to get any required patches back into the upstream repo?

**Comment by andreimatei** [comment]
I think Peter should know why we forked this guy. Was it to support reading multiple result sets per command in the cockroach CLI?
We could probably invent a mechanism where our fork doesn't register under "postgres". Or maybe you don't need to (transitively) import our `pq` at all... How are you using cockroach exactly?

**Comment by petermattis** [comment]
Yes, we added support for reading multiple results to our fork of `lib/pq`. Probably worthwhile to register the driver there as something other than "postgres". We'd also need to make `cockroach-go` import both `lib/pq` and `cockroach/pq` so that we can inspect errors from either. Sigh, that's ugly.

**Comment by ericchiang** [comment]
> How are you using cockroach exactly?

Just with `database/sql` and some custom translation between query flavors. The goal is to support a bunch of DBs with `github.com/cockroachdb/cockroach-go/crdb.ExecuteTx` used for Cockroach. I'm importing both `lib/pq` and `cockroachdb/cockroach-go` which transitively imports `cockroach/pq`. This is fixed when I remove `lib/pq` or `cockroach/cockroach-go`.

**Comment by andreimatei** [comment]
I'm trying to make `cockroach-go` (our client lib) not use our forked `lib/pq` (I don't think it should need it), but the test fails for reasons I'm unsure of... Investigating.

**Comment by andreimatei** [comment]
@ericchiang the PR above is moving `cockroach-go` to the unforked `lib/pq`. Turns out our fork is more resilient to sloppy clients; we should resume the conversations for upstreaming some of the changes.
