### ISSUE TITLE
cockroach-go testserver: Failed to fetch latest binary: error downloading https://binaries.cockroachdb.com/cockroach-v23.2.0.darwin-10.9-amd64.tgz: 404 (404 Not Found) 

### ISSUE THREAD

**Issue by jadhavrajashri14** [cockroachdb/cockroach-go#176]
2024/01/19 13:36:40 GET https://binaries.cockroachdb.com/cockroach-v23.2.0.darwin-10.9-amd64.tgz
2024/01/19 13:36:42 cockroach-go testserver: Failed to fetch latest binary: error downloading https://binaries.cockroachdb.com/cockroach-v23.2.0.darwin-10.9-amd64.tgz: 404 (404 Not Found) attempting to use cockroach binary from your PATH
  cockroach-go testserver command cockroach version failed: exec: "cockroach": executable file not found in $PATH

**Comment by elv-todd** [comment]
dup https://github.com/cockroachdb/cockroach-go/issues/174

**Comment by rafiss** [comment]
please use v2.3.6 to get the fix
