### ISSUE TITLE
binary download should use s3 website endpoint and follow the redirect

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach-go#26]
We currently issue two web requests, first fetching `.LATEST`, then reading its content, and finally downloading the binary itself. Instead, we should hit the "website" endpoint, e.g. http://cockroach.s3-website-us-east-1.amazonaws.com/cockroach/cockroach.darwin-amd64.LATEST, and just follow the redirect.

We should also make that link work over HTTPS, which it currently does not.

Assigning @mberhault for the SSL bit.

**Comment by benesch** [comment]
Ok, https://edge-binaries.cockroachdb.com now points at the `cockroach` S3 bucket. So e.g. https://edge-binaries.cockroachdb.com/cockroach/cockroach.LATEST now properly redirects to the latest master build.

This is moot, though: @bdarnell filed #19 to suggest we download the latest stable release instead.
