### ISSUE TITLE
pgx support

### ISSUE THREAD

**Issue by mgorozii** [cockroachdb/cockroach-go#48]
My issue is connected to #16.
I faced the issue that none of our transactions was retried.
During the investigation, we realized, that in this commit was added the dependency to lib/pq and it handles only errors arisen by pq driver, but we use jackc/pgx. I think we all know, that it's quite popular.
And it isn't clear from [docs](https://www.cockroachlabs.com/docs/stable/build-a-go-app-with-cockroachdb.html#transaction-with-retry-logic)  that there is support only for lib/pq.

Maybe we could find the solution which will be driver independent?

**Comment by andreimatei** [comment]
Indeed...
The problem, of course, is that go's sql package doesn't give you access to any error code, so we cast down to lib/pq errors.
We could also try to cast to pgx errors, or we could recognize the error messages (but that's really brittle as this has changed in the past) instead of the error code, or we could try to get both pq and pgx to export a `Code()` method from their errors and cast to an interface with this method. Unfortunately, it looks to me like at the moment neither of them exposes the code through a method, just a field, so we can't use this trick. I might try to contribute this to both drivers and see how it goes.

**Comment by mgorozii** [comment]
Yes, in Go your approach is the most suitable. It's strange, what neither pgx.PgError nor pq.Error exposes the method to be able to use interface for access. It'll be nice if we could to do this.

Also, we could consider using reflection. Of course, it's more expensive than type assertation, but if we talk about communication with a database it isn't too expensive.

What was the problem with checking error message? From my point of view, checking string in the err.Code is almost the same as checking these codes in err.Error() string.

**Comment by andreimatei** [comment]
Checking the *code* in the err string is weird (what if you're inserting a row with key 40001), but besides that pq doesn't even seen to put the code in the message. I might send a patch for that too.

**Comment by arctica** [comment]
IMHO, the crdb client should be driver agnostic. That means even if the code was casting to pq's and pgx's respective error types, we'd still leave some people who use other drivers or error types stranded and they'll be scratching their heads as to why this is happening. At least it should be clearly documented then which drivers are supported, what can cause this error and how to handle the situation. This is also related the the issue that previously wrapped errors from https://github.com/pkg/errors were causing no automatic retries. I think there is a general issue with the API in terms of error type usage. If there was a concensus amongst drivers (or better the sql package) to expose a Code() method, then that would be a viable solution. I doubt the sql package will change anytime soon. It is possible that pq and pgx will change their packages but maybe in the meantime using reflect to get the Code field from both error types could make sense, it's a string in both cases. But in any case it wouldn't be a silver bullet (see custom error types). I think a clear documentation would go a long way in helping others out to avoid hours of debugging.
