### ISSUE TITLE
Support Go 1.13 error wrapping in ExecuteTx

### ISSUE THREAD

**Issue by F21** [cockroachdb/cockroach-go#52]
Go 1.13 has built in support for error wrapping and unwrapping: https://golang.org/pkg/errors/
There is a transitional package at https://godoc.org/golang.org/x/xerrors

Problem: When using `ExecuteTx`, errors returned from the user supplied function must [wrap the underlying error correctly](https://godoc.org/github.com/cockroachdb/cockroach-go/crdb#ExecuteTx), so that the transaction can be retried. This worked well previously as long as you implemented the `ErrorCauser` interface or use `pkg/errors` to wrap the underlying error.

In Go 1.13, to wrap errors, there is a `%w` placeholder: `fmt.Errorf("error doing something: %w", err)`. You can then use `errors.Unwrap()` to retrieve the underlying error, use `Is` to assert the error type or use `As` to retrieve the error if it matches a type.

I think this package should be updated to support Go 1.13 error wrapping in addition to the current `ErrorCauser` interface as error wrapping using the stdlib's `errors` package is the recommended way, moving forward. We are currently in the process of migrating to Go 1.13 and are dropping `pkg/errors` for stdlib errors where possible.

**Comment by andreimatei** [comment]
Thanks for the hint, @F21. Sent out a fix.
