### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by mattboll** [cockroachdb/cockroach-go#54]
Hi,
It looks like jackc/pgx has been updated and cockroach-go won't compile anymore.
The patch may just be to replace pgx.PgError by *pgconn.PgError

Cheers,

```
--- a/crdb/tx.go
+++ b/crdb/tx.go
@@ -20,7 +20,7 @@ import (
        "context"
        "database/sql"
 
-       "github.com/jackc/pgx"
+       "github.com/jackc/pgconn"
        "github.com/lib/pq"
 )
 
@@ -143,7 +143,7 @@ func errCode(err error) string {
        case *pq.Error:
                return string(t.Code)
 
-       case pgx.PgError:
+       case *pgconn.PgError:
                return t.Code
 
        default:
```

**Comment by tomislavmitic2012** [comment]
Is this going to be addressed at some point in time, this is cause our build environment to break at work, we are installing using gobuffallo/pop and this module is an inderect dependency in compiling that go module. Any suggestions as how to addrss this are most appreciated.

**Comment by mattboll** [comment]
Hi,
I opened the issue due to exact same problem and I ended by using go modules, basically just with "export GO111MODULE=on" before compiling

**Comment by tomislavmitic2012** [comment]
@mattboll did that resolve the issue for you?

**Comment by mattboll** [comment]
@tomislavmitic2012  yes, it works fine now

**Comment by tomislavmitic2012** [comment]
GO111MODULE=on doesn't do anything in golang v 1.13 so that won't help..... this needs to be addressed with a patch.

**Comment by mattboll** [comment]
may be I also had to run "go mod init my/project" to add go.mod and go.sum, I'm using docker to build (with gobuffalo/buffalo:v0.14.10 as builder)

**Comment by andreimatei** [comment]
I'll merge #56 momentarily to fix this
