### ISSUE TITLE
testserver: concurrent downloads

### ISSUE THREAD

**Issue by georgysavva** [cockroachdb/cockroach-go#58]
I have a question about how testserver is handling the concurrent downloading of the cockroach binary.  As I understand through reading the code:
It makes a get request for the latest build, it retrieves the file name and builds the local path where it will save the file.
If local file already exists it does nothing, but if it's not, it creates that file and starts downloading into it.
What happens if two process will try to initiate a testserver. They both check the local file, it doesn't exist, and they both will try to create it and start write to it. 
I think this situation is only possible in ci/cd server when you have multiple concurrent test stages and they are not isolated via Docker.

**Comment by rafiss** [comment]
@georgysavva Thanks for the question. I believe the concurrency issue you describe does not affect the testserver.

As you say, if both processes see that the file does not exist, they will both call the `downloadFile` function to create the file and download into it. The first thing this function does is create the file with `os.OpenFile(filePath, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0200)`. This call will return an error if the file already exists. So one process will successfully create the file, and the other will fail. On most filesystems, this file creation is atomic. For more details, read about the `O_EXCL` flag here: https://linux.die.net/man/2/open.

If you're still affected by the issue, could you please re-open this, and provide a way to reproduce it?

**Comment by georgysavva** [comment]
Thanks for the answer. Everything is clear.
