### ISSUE TITLE
pq library alternatives.

### ISSUE THREAD

**Issue by georgysavva** [cockroachdb/cockroach-go#59]
As I can see from your docs, you propose to use the pq library to connect to Cockroachdb from the application.
After looking at this library I found several major issues in my opinion:
1. It doesn't support read/write timeouts, only connection timeout. So if we get a connection from the pool and network failed the query will hang because we don't have read timeouts.
I found an open issue for this problem: https://github.com/lib/pq/issues/450 it was opened 4 years ago and they still didn't do anything. Another guy did a PR https://github.com/lib/pq/pull/792 but maintainers didn't react on it in a year.
Another postgers library supports such timeouts: https://github.com/go-pg/pg

2. Another issue with the pq, is that if you want to timeout your queries via the context cancel mechanism, it will try to send a cancel request to the server and if it's unreachable it will, again, hang. Here is the opened issue in this regard (3 years old):
https://github.com/lib/pq/issues/620 

I think it goes against the highly available and distributed nature of the CockroachDB. 
Maybe there are some side car proxies that one can use to offload this timeout logic from the library. Like envoy for http. 
So that is your advice in that regard ?

**Comment by andreimatei** [comment]
We actually recommend [pgx](https://github.com/jackc/pgx) as a Go client driver. lib/pq is pretty dead, indeed. I'll ask people to update our docs.
Hopefully https://github.com/go-pg/pg works too.

Does this answer?

**Comment by georgysavva** [comment]
I check the [pgx](https://github.com/jackc/pgx) library too. But it seems that it also only supports the connect_timeout.

**Comment by georgysavva** [comment]
It seems that they implement the desired timeouts vie context timeout. So it's fine.
But what about library functionality overall did you test cockroachDB with pgx for compatibility, are there any issues with it?

**Comment by andreimatei** [comment]
It should work, yeah. We've done some testing with it; I couldn't tell you how much but I trust it more than lib/pq. I'll talk to people about updating our docs.

**Comment by georgysavva** [comment]
Okay, thanks. It answers my question.

**Comment by andreimatei** [comment]
Let us know if you run into any trouble!
