### ISSUE TITLE
pgx: automatic prepared statements

### ISSUE THREAD

**Issue by georgysavva** [cockroachdb/cockroach-go#64]
Does cockroachDB support prepared statement and is it beneficial to use them?
[pgx](https://github.com/jackc/pgx) library creates prepared statements and cache them per connection by default: [docs](https://godoc.org/github.com/jackc/pgx#hdr-Prepared_Statements)
Is this behaviour totally fine for cockroachDB?

**Comment by georgysavva** [comment]
Hi. Any update on this? Thanks!

**Comment by andreimatei** [comment]
Yes, we support them. There's some benefit to using them.

**Comment by georgysavva** [comment]
So generally, there should be no reason to change the default `pgx` behaviour?

**Comment by andreimatei** [comment]
Right.

**Comment by georgysavva** [comment]
Understood. Thanks for your help!
