### ISSUE TITLE
allow concurrent tests with testserver when binary is being downloaded

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach-go#7]
if two tests using the testserver are running concurrently (often when testing multiple packages), we may end up with one test starting the download, and another thinking the file is there (we only look for filenames).
This obviously causes the second test to fail since the binary file is still busy.

Possible solutions:
* tmp file names for the binary: kindda crappy, we'd have to download it for every single test
* tmp file that gets renamed: the binary would still get downloaded as many times as it takes for the first test to finish.
* lock file until the download is finished: would make all the other tests wait and only download once. any issues if the downloader dies? the test fails anyway.
* initOnce statement somewhere to download: this works if the test runner is a go binary that's running all tests, otherwise not so much.

**Comment by spencerkimball** [comment]
I like the third option.

If binary file doesn't exist:
1. create empty binary file if it doesn't exist (should fail if it does already exist)
2. flock(LOCK_EX)
3. download binary
4. flock(LOCK_UN)

If binary file already exists:
1. flock(LOCK_SH) <- will block until it's downloaded
2. maybe original downloader failed? need to handle errors here and potentially try downloading ourselves.

**Comment by mberhault** [comment]
flock is a bit weird actually, you need to create the file first, and it doesn't buy us much, it's just as simple to use a custom file for this.

But I thought of another option, simply create the file with 0600 (rw) while downloading (or even 0200 (write only)), then chmod it when successfully downloaded. The consumer already stats the file to see if it exists, we just need to check the mode (looking for the execute bit) and loop on that.

Concurrent downloads should still work the same, at some point, we're relying on the creation of a single file to indicate work has started.
