### ISSUE TITLE
Go modules version is broken

### ISSUE THREAD

**Issue by georgysavva** [cockroachdb/cockroach-go#79]
Hi! Sorry to bother you again :) But the modules version isn't go getable anymore:
```
go get  github.com/cockroachdb/cockroach-go/v2
```
Returns an error:
```
go get github.com/cockroachdb/cockroach-go/v2: github.com/cockroachdb/cockroach-go/v2@v2.0.1: invalid version: missing github.com/cockroachdb/cockroach-go/go.mod and .../v2/go.mod at revision v2.0.1
```
As I understand this happens because tag `v2.0.1` is set on commit from the `master`, not the `version-module` branch:
https://github.com/cockroachdb/cockroach-go/tree/v2.0.1
And repository at this commit doesn't contain any information about Go modules.

**Comment by rafiss** [comment]
@georgysavva Thanks for this report! It's not a bother at all. You're right. We have an open PR (#78) to merge the `version-module` branch in, but as you say, the `v2.0.1` tag should not be applied to that commit on `master`. I'll try to unpublish this tag, then once #78 is complete, I will publish a new tag.

cc @asubiotto -- planning to do the above, but if it interferes with something you're relying on, let me know.

**Comment by rafiss** [comment]
Removed `v2.0.1`

**Comment by georgysavva** [comment]
Thanks for the fix! BTW, making `cockroach-go` modules aware by default is great news.
