### ISSUE TITLE
Feature: support go-pg/pq

### ISSUE THREAD

**Issue by hazcod** [cockroachdb/cockroach-go#86]
Since pq uses `pg.DB` instead of `sql.DB`, the crdb package is unable to be used with `pg`.

**Comment by rafiss** [comment]
I took a look at the go-pg code, and it seems like it already has functionality to retry on serialization errors: https://github.com/go-pg/pg/blob/d3b6c7c71d8d78bde6f106132340a2ff37cf5a4a/base.go#L180

Just curious if you've tried that out. Could you explain more what functionality you want? Thanks!

**Comment by hazcod** [comment]
@rafiss you are absolutely right, not sure how I missed that one.
I am closing. Thanks!
