### ISSUE TITLE
Upgrade GORM helper to use GORM v2

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach-go#94]
We are using https://github.com/jinzhu/gorm which is not maintained now.

The project is now at https://github.com/go-gorm/gorm

**Comment by markdiener10** [comment]
Hello Rafiss.  I see you are taking my suggestion at upgrading the library.

**Comment by xuhui-lu** [comment]
hello @rafiss , I am a junior contributor in cockroachdb community. May I get a chance to work on this issue?

**Comment by rafiss** [comment]
@xuhui-lu sure, we would welcome and appreciate your contribution!

**Comment by markdiener10** [comment]
Rafiss, you can grab the commit from 28 days ago, I changed the cockroach-go to use GORM v2.  You just need to talk to the people from our project meeting.

**Comment by xuhui-lu** [comment]
oh, so is this issue solve already?

**Comment by rafiss** [comment]
@markdiener10 Thanks for the reminder! :)  Unfortunately I won't have the time to coordinate with the people from that meeting about getting the code.

We'd welcome a PR on this issue. I'll be able to review the code once something is submitted here. So @xuhui-lu we would still welcome your contribution.

**Comment by markdiener10** [comment]
Let me see what I can do.

**Comment by xuhui-lu** [comment]
cool, thanks for the info.

**Comment by xuhui-lu** [comment]
@rafiss I just submitted a PR for this issue, could you help me review it?

**Comment by rafiss** [comment]
closed by #95
