### ISSUE TITLE
Should be 25P02 retriable?

### ISSUE THREAD

**Issue by lopezator** [cockroachdb/cockroach-go#97]
We are having problems in our tests, mainly are `40001` errors.

I integrated the fantastic `cockroach-go` retry mechanism by wrapping pgx here: 

https://github.com/lopezator/crdbx

The retry mechanism here helps, but I wasn't able to pass all tests due to some weird `25P02` errors.

Should this error code be retriable?

```
user_test.go:1163: request failed: crdb: failed to execute a one query for users: bind failed to execute query: ERROR: current transaction is aborted, commands ignored until end of transaction block (SQLSTATE 25P02)
```

I suspected this was due to some `t.Parallel` issuing `UPDATE` stmts over the same set of data simultaneously, so I just changed the seed data for the conflicting tests and worked, but we obviously cannot rely on this.

Maybe is just something that has to be fixed on `cockroachdb` and not here, but we could retry those errors here in the meantime... 

Thoughts?

**Comment by nvanbenschoten** [comment]
The `25P02` error indicates that you continued to issue statements within the context of a failed transaction. This could be an indication of improper error handling. When a transaction returns an error during the execution of any of its statements, this needs to be propagated back up to the `cockroach-go` retry wrapper.

Do you know exactly which transaction is hitting this error?

**Comment by lopezator** [comment]
This happens in our tests very frequently.

We are using this for our tests, to avoid seeding/cleaning up on every test:

https://github.com/DATA-DOG/go-txdb

Changes happen inside the same transaction, so the issue might be related with this?

What is confusing also is that the 25P02 are not consistent, sometimes raise, sometimes don't. 

Is there any kind of race condition I guess?

**Comment by nvanbenschoten** [comment]
> Changes happen inside the same transaction, so the issue might be related with this?

Could you expand on this? You don't mean that you are performing concurrency operations within a transaction, do you?

**Comment by lopezator** [comment]
> Could you expand on this? You don't mean that you are performing concurrency operations within a transaction, do you?

Nope, my feeling is that different transactions are competing, producing the error.

If I reproduce the scenario of a `40001` error (with different transactions in different `t.Parallel` tests updating some particular row), and then I add the retry mechanism provided by `Execute` function by using [my own driver](https://github.com/lopezator/crdbx) then, the `40001`s disappear, producing `25P02`s (sometimes).

I could elaborate and share an example reproducing this if you find it interesting.

**Comment by rafiss** [comment]
Thanks for the report and your work on `crdbx`! 

I'd be interested in learning a bit more. If you have a reliable repro, it would be interesting to see the database exec logs. You can enable these logs with a command like this:
```
./cockroach start-single-node --insecure --store=store --logtostderr --vmodule=exec_log=2 2> stderr.log
```

**Comment by lopezator** [comment]
Hello @rafiss thanks for your response!

I've uploaded an small project that reproduces this here:

https://github.com/lopezator/crdb-25P02

**Comment by lopezator** [comment]
The issue was on our end.

Txdb opens a transaction for every test. In table-test scenarios, although we were issuing (apparently) non-conflicting stmts (see the example), they were inside the same transaction and this was the cause of the `25P02`s. Creating a new transaction for every sub-test (moving the `openDB()` inside the `t.Run`), fixed the issue.

Thank you for the support and sorry for any inconvenience caused.

**Comment by rafiss** [comment]
I'm glad you were able to find the issue!
