### ISSUE TITLE
Second call to Start() throws error

### ISSUE THREAD

**Issue by danieloliveira079** [cockroachdb/cockroach-go#98]
The current [documentation](https://github.com/cockroachdb/cockroach-go/blob/master/testserver/testserver.go#L30) instructs that the method `Start` should be called after creating a new test server. However, calling this method throws the error: `Start() can only be called once`

https://github.com/cockroachdb/cockroach-go/blob/master/testserver/testserver.go#L30

```
ts, err := testserver.NewTestServer()
if err != nil {
    t.Fatal(err)
}

if err := ts.Start(); err != nil { 
    t.Fatal(err) <== "Start() can only be called once"
}

defer ts.Stop()
```

The first call to the method is happening in https://github.com/cockroachdb/cockroach-go/blob/master/testserver/testserver.go#L328.

Expected:
Remove the following block from he documentation.

```
if err := ts.Start(); err != nil { 
    t.Fatal(err)
}
```

**Comment by rafiss** [comment]
Thank you for noticing this! The docs were not updated to account for https://github.com/cockroachdb/cockroach-go/pull/74
